In [1]:
%pip install pandas numpy matplotlib

Requirement already satisfied: pandas in c:\Users\Kenji\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy in c:\Users\Kenji\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.5.1)
Requirement already satisfied: matplotlib in c:\Users\Kenji\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.11.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\Kenji\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\Kenji\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\Kenji\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (1.4.0)
Requirement already satisfied: cycler>=0.10 in c:\Users\Kenji\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\Users\Kenji\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (4.66.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\Kenji\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (1.5.1)
Requirement already satisfied: packaging>=20.0 in C:\Users\Kenji\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in c:\Users\Kenji\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\Kenji\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (3.3.3)
Requirement already satisfied: six>=1.5 in c:\Users\Kenji\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [3]:
print(pd.__version__)

3.0.5

In [5]:
ruta_1 = r"C:\Users\Kenji\Desktop\Fondo Mivivienda\mivivienda.csv"
vivienda = pd.read_csv(ruta_1)
display(vivienda.head())

,FECHA_DESEMBOLSO,PRODUCTO,DEPARTAMENTO,PROVINCIA,DISTRITO,UBIGEO,IFI,TIPO_IFI,MONTO_CREDITO,MONTO_CUOTA_INICIAL,PLAZOS,TASA,MONTO_VALOR_VIVIENDA,FECHA_CORTE
0,20200107,NCMV,LIMA,LIMA,CHORRILLOS,150108,CREDITO,BANCO,300357.96,34374.3,228.0,7.10,343743.0,20230811
1,20200107,NCMV,LAMBAYEQUE,LAMBAYEQUE,LAMBAYEQUE,140301,CREDITO,BANCO,79800.00,24398.0,180.0,8.20,121990.0,20230811
2,20200107,NCMV,LIMA,LIMA,RIMAC,150128,CREDITO,BANCO,62798.08,19990.0,120.0,8.30,99900.0,20230811
3,20200107,NCMV,LIMA,LIMA,ATE,150103,CREDITO,BANCO,162062.14,19992.0,240.0,7.50,199916.0,20230811
4,20200107,NCMV,LAMBAYEQUE,CHICLAYO,CHICLAYO,140101,CREDITO,BANCO,97500.00,19500.0,240.0,10.45,130000.0,20230811

In [7]:
# Numero de filas, columnas
print(vivienda.shape)

(55568, 14)

In [8]:
# Para analizar columnas, axis = 1
nr_nulo = vivienda.isna().all(axis=1).sum()
print(nr_nulo)
# dropna() elimina todos los registros que tengan nulos
if nr_nulo > 0:
    vivienda = vivienda.dropna()
    print(vivienda.shape)

0

In [9]:
# Verificar si el registro tiene datos duplicados
nr_duplicado = vivienda.duplicated().sum()
print(nr_duplicado)
# Eliminamos filas duplicadas
if nr_duplicado > 0:
    vivienda = vivienda.drop_duplicates()
    # Mostramos filas actuales (0)
    print(vivienda.shape[0])
print(vivienda.shape)

435
55133
(55133, 14)

In [10]:
# Eliminamos la columna FECHA_CORTE
vivienda = vivienda.drop("FECHA_CORTE", axis=1)
print("Filas válidas finales: ", vivienda.shape[0])

Filas válidas finales:  55133

In [16]:
display(vivienda)

,FECHA_DESEMBOLSO,PRODUCTO,DEPARTAMENTO,PROVINCIA,DISTRITO,UBIGEO,IFI,TIPO_IFI,MONTO_CREDITO,MONTO_CUOTA_INICIAL,PLAZOS,TASA,MONTO_VALOR_VIVIENDA
0,20200107,NCMV,LIMA,LIMA,CHORRILLOS,150108,CREDITO,BANCO,300357.96,34374.3,228.0,7.10,343743.0
1,20200107,NCMV,LAMBAYEQUE,LAMBAYEQUE,LAMBAYEQUE,140301,CREDITO,BANCO,79800.00,24398.0,180.0,8.20,121990.0
2,20200107,NCMV,LIMA,LIMA,RIMAC,150128,CREDITO,BANCO,62798.08,19990.0,120.0,8.30,99900.0
3,20200107,NCMV,LIMA,LIMA,ATE,150103,CREDITO,BANCO,162062.14,19992.0,240.0,7.50,199916.0
4,20200107,NCMV,LAMBAYEQUE,CHICLAYO,CHICLAYO,140101,CREDITO,BANCO,97500.00,19500.0,240.0,10.45,130000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
55563,20241227,S-CRC,LIMA,LIMA,MAGDALENA DEL MAR,150120,Credito,Banco,360000.00,40000.0,168.0,9.35,400000.0
55564,20241227,S-CRC,LIMA,LIMA,SAN MIGUEL,150136,Credito,Banco,423000.00,47000.0,240.0,9.24,470000.0
55565,20241227,S-CRC,LIMA,LIMA,BRENIA,150105,Credito,Banco,346680.00,38520.0,240.0,10.19,385200.0
55566,20241227,S-CRC,LIMA,LIMA,LIMA,150101,Credito,Banco,292106.00,97369.0,180.0,9.20,389475.0
55567,20241227,S-CRC,LIMA,LIMA,LOS OLIVOS,150117,Interbank,Banco,323969.15,80180.0,240.0,8.00,400900.0

In [13]:
ruta_archivo = r"C:\Users\Kenji\Desktop\Fondo Mivivienda\limpio_mivivienda.csv"
vivienda.to_csv(ruta_archivo, index=False)